#ifndef CONFIG_H
#define CONFIG_H

#define EMU_WINDOW_TITLE "Chip 8 Emulator"
#define CHIP8_MEM_SIZE 4096
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define CHIP8_WINDOW_MULTIPLIER 10

#define DATA_REGISTERS_COUNT 16
#define TOTAL_STACK_DEPTH 16

#define TOTAL_KEYS 16

#define CHIP8_CHAR_SET_LOAD_ADDRESS 0x00


#endif